name: Cache Demo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/my-demo
          key: cache-b925b7e

      - name: prime-cache-b925b7e
        run: echo "cache-hit = ${{ steps.cache-deps.outputs.cache-hit }}"
